### ISSUE TITLE
No twitter popup when twitter feed is embedded in the page

### ISSUE THREAD

**Issue by mishac** [heiseonline/shariff#339] opened 2018-09-13 17:52 UTC
This appears to be the opposite of this issue https://github.com/heiseonline/shariff/pull/201

In that issue the twitter popup opened twice when twitter's widget.js was loaded in the page.  We're having an issue where *no* twitter popup comes up when the twitter button is clicked.  I'm not sure if it's related or not.

**Comment by srich3** [comment] 2019-05-16 18:43
I am having this same issue.
Twitter-feed and twitter-share-button on the same page.
Click the twitter button.
nothing happens.

The twitter-share-button works fine on other pages without twitter-feeds.

**Comment by richard67** [comment] 2019-05-21 19:59
It really seems that PR #201 caused that issue after it has been merged.

@Nebel54 as the author of PR #201 : Any idea on how to fix that?

**Comment by Nebel54** [comment] 2019-05-22 08:20
I just gave it a try with a vanilla shariff integration: https://codepen.io/anon/pen/zQpxwr?editors=1111 and the pop-up works as expected. Do you see any errors in you Javascript-Console? Can you send an example link where the problem appears?

**Comment by pivica** [comment] 2020-07-15 15:18
Have the same problem on a Drupal 8 site with [Shariff contrib module](https://www.drupal.org/project/shariff) integration. Found out that the problem is that Drupal integration is adding additional JS code that is preventing propagation on click event to document root and then twitter widget JS event handling code will not be triggered resulting in no Twitter popup widget shown. I guess this code was added to prevent duplicate popups and now integration does not work because of https://github.com/heiseonline/shariff/pull/201 fix.

This is already fixed in the latest dev version of Drupal shariff integration in https://www.drupal.org/node/3108089.

If you are running a custom integration then make sure that no JS code is preventing propagation of click event on twitter share button.

**Comment by pivica** [comment] 2020-07-16 13:17
One additional thing about this. It seems that twitter button with twitter widget is now opening in a new tab instead of a popup. Sounds more like a follow-up, just want to report it here.

**Closed** 2023-03-25 21:55 UTC
