### ISSUE TITLE
How to set "Shariff PHP Backend" ?

### ISSUE THREAD

**Issue by ZenImagine** [heiseonline/shariff#331] opened 2018-05-26 23:59 UTC
https://www.drupal.org/project/shariff

I have trouble setting up "Shariff PHP Backend", can you help me?

I downloaded the archive (7.1.1) on:

https://github.com/heiseonline/shariff-backend-php/releases

Then I copy it to the root of my Drupal site and unzipped.

`/public_html/web/shariff-backend-php`

My domain name is https://www.s1biose.com

`cd /public_html/web/shariff-backend-php`

nano index.php

```
<?php

require_once __DIR__.'/vendor/autoload.php';

use Heise\Shariff\Backend;

/**
 * Demo Application using Shariff Backend
 */
class Application
{
    /**
     * Sample configuration
     *
     * @var array
     */
    private static $configuration = [
        'cache' => [
            'ttl' => 60
        ],
        'domains' => [
            'www.s1biose.com'
        ],
        'services' => [
            'Facebook',
            'LinkedIn',
            'Reddit',
            'StumbleUpon',
            'Flattr',
            'Pinterest',
            'Xing',
            'AddThis',
            'Vk'
        ]
    ];

    public static function run()
    {
        header('Content-type: application/json');

        $url = isset($_GET['url']) ? $_GET['url'] : '';
        if ($url) {
            $shariff = new Backend(self::$configuration);
            echo json_encode($shariff->get($url));
        } else {
            echo json_encode(null);
        }
```
/public_html/web/

should I copy the files to the root or outside?

/public_html/web/

or

/public_html/

thank you
![capture du 2018-04-22 03-01-17](https://user-images.githubusercontent.com/29839861/40581164-acce1ffa-6151-11e8-83de-dd8b5752f180.png)
![capture du 2018-04-22 03-15-28](https://user-images.githubusercontent.com/29839861/40581166-b14db8d8-6151-11e8-8fd1-0abbbe6430d5.png)
![capture du 2018-04-22 03-16-20](https://user-images.githubusercontent.com/29839861/40581167-bcf7140e-6151-11e8-9210-f9bb0f4ab45a.png)

**Comment by liayn** [comment] 2018-05-27 08:40
This is the wrong place to ask for help for/with Drupal.
Maybe https://www.drupal.org/project/issues/shariff?status=All&categories=All is better.

**Comment by ZenImagine** [comment] 2018-05-27 11:35
I already asked the question about the Drupal module and he told me to ask it here
https://www.drupal.org/project/shariff/issues/2963009

**Comment by liayn** [comment] 2018-05-27 12:01
Ah sorry, I didn't know that this Drupal module is only for the buttons and not the backend.

All I can tell is that you posted the content of `index.php` above, but your screens refer to a `shariff-backend.php`, so I guess there is something wrong.
Also check your webserver logs, they will tell you why a 403 error was issued.

**Comment by liayn** [comment] 2018-05-27 12:13
This is also kind of a duplicate of https://github.com/heiseonline/shariff-backend-php/issues/142.

Please continue things there, because this repo is not about backends.

**Comment by ZenImagine** [comment] 2018-05-27 12:15
Thank you I will open a problem on the right project

**Comment by liayn** [comment] 2018-05-27 12:17
Thanks. And close this one then.

**Closed** 2018-05-27 12:28 UTC
