### ISSUE TITLE
WhatsApp doesn't open

### ISSUE THREAD

**Issue by silas229** [heiseonline/shariff#352] opened 2019-02-04 20:03 UTC
When I click on my smartphone on the WhatsApp share button with WhatsApp installed, it won't open.
Screenshot: ![](https://cloud.silas229.de/index.php/s/Xiaok8HqgRBd7qi/preview)

**Comment by silas229** [comment] 2019-02-04 20:06
Maybe the link must point to wa.me: https://faq.whatsapp.com/en/android/26000030/

**Comment by richard67** [comment] 2019-02-09 15:46
@silas229 No, the link you refer to is something else. It sais it is about sending messages to people without knowing their phone number.

Furthermore, I can't reproduce your issue with Android 6.0.1 on a Samsung Galaxy S5 mini. When I touch the Whatsapp button in the 2nd example of the Shariff demo page, Whatsapp opens and wants me to select a contact to send the link to, including an option at the top to send to all my contacts.

Maybe you can post some version info here about your Android and WhatsApp and browser and which kind of phone you use, so other visitors here who have suitable equipment could try to reproduce your issue?

`whatsapp://send?text=` still seems to be the valid sharing method for WhatsApp, at least on [https://github.com/vinkla/shareable-links/blob/master/README.md](https://github.com/vinkla/shareable-links/blob/master/README.md), which is my favourite source for sharing links, still sais so.

**Comment by philwolstenholme** [comment] 2019-10-10 16:51
The link @silas229 posted (or the general version [here](https://faq.whatsapp.com/en/general/26000030/?category=5245251)) is correct:

> To create a link with just a pre-filled message, use https://wa.me/?text=urlencodedtext
> 
> Example:https://wa.me/?text=I'm%20inquiring%20about%20the%20apartment%20listing

Using the https://wa.me URL means that the sharing link will work on mobile devices _and_ in a desktop web browser

**Comment by richard67** [comment] 2020-07-21 10:54
Will be fixed by pull request #381 ,

**Closed** 2020-09-21 20:13 UTC
