### ISSUE TITLE
Problem with share counting.

### ISSUE THREAD

**Issue by nortmas** [heiseonline/shariff#244] opened 2017-07-20 05:09 UTC
Found a bug. Share counting doesn't work. Seems like bug in shariff.js
`_updateCounts: function(success, data) {`
but should be
`_updateCounts: function(data, success) {`

**Comment by nortmas** [comment] 2017-07-20 05:17
in master branch it looks:
`_updateCounts(err, data) {`
but seems should be
`_updateCounts(data, err) {`

Help link: http://api.jquery.com/jquery.getjson/

> Function( PlainObject data, String textStatus, jqXHR jqXHR )

**Comment by pmb0** [comment] 2017-07-20 06:38
Hi @nortmas, thanks for reporting. We do not use jQuery in Shariff any longer. Our implementation of `getJSON` passes `error, data, xhr` arguments to the callback function, see https://github.com/heiseonline/shariff/blob/master/src/js/dom.js#L430.

> Share counting doesn't work.

What version of Shariff did you use?

**Comment by liayn** [comment] 2017-07-20 06:41
>  jQuery in Shariff any longer

That's not true. There is both versions. The complete edition uses the custom DOM, otherwise jQuery is used.

This is indeed an interesting finding, since we use it with jquery on a site and stats are displayed. Weird.
By reading the docs, this callback is indeed wrong.

**Comment by pmb0** [comment] 2017-07-20 06:46
Ah, i did not know about https://github.com/heiseonline/shariff/blob/master/package.json#L75. @liayn What do you think about entirely dropping jQuery from Shariff?

**Comment by liayn** [comment] 2017-07-20 06:48
> we use it with jquery on a site and stats are displayed. Weird.

Not so weird. My mistake. We use 1.24.1 there. So problem confirmed.

Against dropping it. Why should I include yet another DOM lib if I have jQuery on the site anyways. You have the free choice. If you have jQuery already anyways, go with the min version, otherwise use the complete one.

**Comment by liayn** [comment] 2017-07-20 06:50
@nortmas Can you push a fix? I propose to align the DOM.js lib with jQuery and swap the two params.

**Comment by pmb0** [comment] 2017-07-20 06:56
Ok, I will align our custom implementation with jQuery's method.

**Comment by nortmas** [comment] 2017-07-20 10:08
I used last version 1.25.2 via composer. Actually I use it in a conjunction with drupal module. (jQuery included by default) Seems DOM.js was not included to this version so it didn't work.

@liayn seems like you better now what to do ;)

**Comment by pmb0** [comment] 2017-07-20 11:45
@nortmas should be fixed now in master. Feel free to re-open this issue otherwise. The fix will be included in our next release.

**Closed by pmb0** 2017-07-20 11:45 UTC

**Comment by nortmas** [comment] 2017-07-20 12:14
@pmb0 Thx! :+1:

**Comment by mmodler** [comment] 2017-07-25 07:59
Can you make a release please? I also have no share count atm...

**Comment by pmb0** [comment] 2017-07-25 08:13
@mmodler Some release-related work still needs to be done. I think we should get there by Friday.

**Comment by mmodler** [comment] 2017-07-25 09:57
@pmb0 Thanks, i'm really looking forward to it :) I'm too stupid to fix it in the minified file ;)
