### ISSUE TITLE
Change WP-Repo Name from "Shariff Wrapper" to "Shariff - Social Media Sharing Buttons with Privacy"

### ISSUE THREAD

**Issue by MaximPro** [heiseonline/shariff#323] opened 2018-05-16 09:52 UTC
Hi,

Much thanks for developing this amazing plugin!!
Wich is really much needed, basically by everyone who knows the crazy tracking that is going on...

From a Marketing Perspective, no one searches in Wordpress Plugin Search for this specific Name, except he/she knew it already. Most people just search something like Social Media, Sharing Buttons etc.

So it would be clever to put some nice Keywords into the Plugin Title, so it get's installed much more often.

My suggestions would be:
Change Name from WP-Repo-Name: "Shariff Wrapper" to "**Shariff - Social Media Sharing Buttons with Privacy**"

That would be really clever and people could find it much easier, without having to know it's existence in the first place. But they could just "discover" it via Plugin Search, wich most people just do.

Probably this one little Change alone could improve the Download-Counter by far the most ;)

Best regards
Maxim ;)

**Comment by richard67** [comment] 2018-05-16 10:27
It seems you posted to the wrong repository. It should be https://wordpress.org/plugins/shariff/

**Comment by 3UU** [comment] 2018-05-16 11:12
It is https://github.com/3UU/wordpress-shariff-wrapper ;-)

The problem is that I have started with the WP plugin really as a wrapper for Shariff. Meanwhile JP and me have done a recode to enable much better handling within WP, many people of the users community have given much input and some code, it has got its own backend... 
But we try to be backward compatible to Shariff functionality and also to the WP plugin by "Heise Zeitschriften Verlag / Yannik Ehlert".  We do not want get in trouble with the Heise Verlag because the guys have done a great work.
 
Therefor the name is like it is.

p.s.: Many thanks to all developers of Shariff because of the great idea and ongoing development! But I think you can close this request here ;-)

**Comment by compeak** [comment] 2018-05-16 12:08
@MaximPro This is not the repository you were looking for.

> My suggestions would be:
Change Name from WP-Repo-Name: "Shariff Wrapper" to "Shariff - Social Media Sharing Buttons with Privacy"

I would strongly recommend against that.

> That would be really clever

No, it wouldn't be.

> Therefor the name is like it is.

@3UU Thank you.

> Many thanks to all developers of Shariff because of the great idea and ongoing development!

I really like how far Shariff is going thanks to the work being done by the great community.

**Closed by compeak** 2018-05-16 12:08 UTC
